#!/usr/bin/python
import MySQLdb
import time
import datetime
def convertTime(a):
	time=datetime.datetime.strptime(str(a), '%H:%M:%S')
	time=time.strftime("%H:%M:%S")
	return time

db = MySQLdb.connect(host="localhost", # your host, usually localhost
                     user="pi", # your username
                      passwd="raspberry", # your password
                      db="thermostat") # name of the data base

# you must create a Cursor object. It will let
#  you execute all the query you need
cur = db.cursor() 


	# pull generated temperatures from db
	#cur.execute("SELECT * FROM Temperatures")

	
	# store averaged temperture into the Conditions table
	#cur.execute("""UPDATE Conditions SET Temp=%s""",(avgTemp))
	#db.commit()

	# read stored average
	#cur.execute("SELECT * FROM Conditions")
	#for row in cur.fetchall() :
		#print row[0]
		#$avgTemp=row[0];

dow=time.strftime("%a")
print (dow)
currentTime=time.strftime("%H:%M:%S")
print (currentTime)
cur.execute("SELECT Start, Stop, Target FROM Schedule WHERE DOW=%s",(dow))
for row in cur.fetchall() :
	#start=datetime.datetime.strptime(str(row[0]), '%H:%M:%S')
	#end=datetime.datetime.strptime(str(row[1]), '%H:%M:%S')
	#start=start.strftime("%H:%M:%S")
	#end=end.strftime("%H:%M:%S")
	start=convertTime(row[0])
	end=convertTime(row[0])
	print (start)
	print (end)
	#print (row[0])
	#print (row[1])
	#print (row[2])
	
	if currentTime>=start and currentTime<=end :
		print ("current time is in the schedule")
	else :
		print ("not in schedule")
