#!/usr/bin/python
import MySQLdb
import time
import datetime

db = MySQLdb.connect(host="localhost", # your host, usually localhost
                     user="pi", # your username
                      passwd="raspberry", # your password
                      db="thermostat") # name of the data base

# you must create a Cursor object. It will let
#  you execute all the query you need
cur = db.cursor() 

#Find target
dow=time.strftime("%a")
currentTime=time.strftime("%H:%M:%S")
cur.execute("SELECT Target, Start, Stop FROM Schedule WHERE DOW=%s AND %s BETWEEN Start AND Stop ",(dow, currentTime))
#insert error handling for conflicting schedules, make php scheduling page check for overlap
for row in cur.fetchall() :
	target=row[0]	
	start=row[1]
	stop=row[2]

print ("target: ", target)
print ("start: ", start)
print ("stop: ", stop)