#!/usr/bin/python
import MySQLdb
import random
import time
import datetime

db = MySQLdb.connect(host="localhost", # your host, usually localhost
                     user="pi", # your username
                      passwd="raspberry", # your password
                      db="thermostat") # name of the data base

# you must create a Cursor object. It will let
#  you execute all the query you need
cur = db.cursor() 

while True:

# to be replaced with thermometer readings
###############################################################################################
	#Generate 10 temperatures 
	i=0
	while (i<10):
		genTemp=random.uniform(55,105)
		cur.execute("""UPDATE Temperatures SET Temp=%s WHERE PID=%s""",(genTemp,i))
		db.commit()
		i=i+1
		time.sleep(2)
###############################################################################################
	wiggle=2
	# pull generated temperatures from db
	cur.execute("SELECT * FROM Temperatures")

	# average all the temperture cells of all the rows
	sumTemp=0
	for row in cur.fetchall() :
		sumTemp=sumTemp+row[1]
	print sumTemp
	avgTemp=sumTemp/10.0
	
	# store averaged temperture into the Conditions table
	cur.execute("""UPDATE Conditions SET Temp=%s""",(avgTemp))
	db.commit()

	# read stored average, probably not necessary. look at removing
	cur.execute("SELECT * FROM Conditions")
	for row in cur.fetchall() :
		avgTemp=row[0]
		print (avgTemp)

	#Find target
	dow=time.strftime("%a")
	currentTime=time.strftime("%H:%M:%S")
	cur.execute("SELECT Target FROM Schedule WHERE DOW=%s AND %s BETWEEN Start AND Stop ",(dow, currentTime))
	#insert error handling for conflicting schedules, make php scheduling page check for overlap
	for row in cur.fetchall() :
		target=row[0]
		print (target)
	cur.execute("UPDATE Conditions SET Target=%s",(target))
	db.commit()


	maxTemp = target+wiggle
	minTemp = target-wiggle

	if avgTemp>=minTemp and avgTemp<=maxTemp :
		#do nothing
		print ("we're perfect at", avgTemp)

	elif avgTemp<minTemp :
		#check to see if heater and fan are running
		#if not, turn them on
		print ("Heat is needed. Too cold at", avgTemp)
		cur.execute("""UPDATE Conditions SET Heat=1, AC=0, Fan=1""")
		db.commit()

	elif avgTemp>maxTemp :
		#check to see if AC and fan are running
		#if not, turn them on
		print ("AC is needed. Too hot at", avgTemp)
		cur.execute("""UPDATE Conditions SET Heat=0, AC=1, Fan=1""")
		db.commit()

