#!/usr/bin/python
import MySQLdb
import random
import time
import datetime
import os
import glob

db = MySQLdb.connect(host="localhost", # your host, usually localhost
                     user="pi", # your username
                      passwd="raspberry", # your password
                      db="thermostat") # name of the data base

# you must create a Cursor object. It will let
#  you execute all the query you need
cur = db.cursor() 

#set up thermometer data
os.system('modprobe w1-gpio')
os.system('modprobe w1-therm')
 
base_dir = '/sys/bus/w1/devices/'
device_folder = glob.glob(base_dir + '10*')[0]
device_file = device_folder + '/w1_slave'

def read_temp_raw():
	f = open(device_file, 'r')
	lines = f.readlines()
	f.close()
	return lines
 
def read_temp():
	lines = read_temp_raw()
	while lines[0].strip()[-3:] != 'YES':
		time.sleep(0.2)
		lines = read_temp_raw()
	equals_pos = lines[1].find('t=')
	if equals_pos != -1:
		temp_string = lines[1][equals_pos+2:]
		temp_c = float(temp_string) / 1000.0
		temp_f = temp_c * 9.0 / 5.0 + 32.0
		return temp_f

while True:

	#grab 10 temperatures 
	i=0
	while (i<10):
		#genTemp=random.uniform(55,105)
		temp=read_temp()
		print (temp)
		cur.execute("""UPDATE Temperatures SET Temp=%s WHERE PID=%s""",(temp,i))
		db.commit()
		i=i+1
		time.sleep(2)

	wiggle=2
	# pull generated temperatures from db
	cur.execute("SELECT * FROM Temperatures")

	# average all the temperture cells of all the rows
	sumTemp=0
	for row in cur.fetchall() :
		sumTemp=sumTemp+row[1]
	print sumTemp
	avgTemp=sumTemp/10.0
	
	# store averaged temperture into the Conditions table
	cur.execute("""UPDATE Conditions SET Temp=%s""",(avgTemp))
	db.commit()

	# read stored average, probably not necessary. look at removing
	cur.execute("SELECT * FROM Conditions")
	for row in cur.fetchall() :
		avgTemp=row[0]
		print (avgTemp)

	#Find target
	#dow=time.strftime("%a")#as three letter
	dow=time.strftime("%w")#as int starting sun=0
	currentTime=time.strftime("%H:%M:%S")
	cur.execute("SELECT Target FROM Schedule WHERE DOW=%s AND %s BETWEEN Start AND Stop ",(dow, currentTime))
	#insert error handling for conflicting schedules, make php scheduling page check for overlap
	for row in cur.fetchall() :
		target=row[0]

	#check for manual overrides
	#need to work on resetting manual temp at schedule change. 
	#For now, once we hit the manual temp we go back to scheduling. This is not optimal but easy.
	cur.execute("SELECT * FROM User_Req")
	for row in cur.fetchall() :
		userReqHeat=row[0]
		userReqAC=row[1]
		userReqFan=row[2]
		manualTemp=row[3]

	if manualTemp>0 :
		target=manualTemp

	print (target)
	cur.execute("UPDATE Conditions SET Target=%s",(target))
	db.commit()
	
	maxTemp = target+wiggle
	minTemp = target-wiggle

	#Check if user wants AC or Heat running and if fan is in Auto/On
	#Once target is hit, if there is a manual override temp in place, go back to schedule temps.
	if avgTemp>=minTemp and avgTemp<=maxTemp :
		#Turn off Heat, AC, Fan unless Fan is set to Auto
		print ("we're perfect at", avgTemp)
		if userReqFan==0 :#Auto fan
			cur.execute("""UPDATE Conditions SET Heat=0, AC=0, Fan=0""")
			db.commit()
			if manualTemp>0 :
				cur.execute("""UPDATE User_Req SET Temp=0""")
				db.commit()
		else : #User wants fan on
			cur.execute("""UPDATE Conditions SET Heat=0, AC=0, Fan=1""")
			db.commit()
			if manualTemp>0 :
				cur.execute("""UPDATE User_Req SET Temp=0""")
				db.commit()

	#home is cooler than target
	elif avgTemp<minTemp :
		print ("Heat is needed. Too cold at", avgTemp)
		if userReqAC==1 : #we're cool enough, let house warm naturally
			if userReqFan==0 : #auto fan
				cur.execute("""UPDATE Conditions SET Heat=0, AC=0, Fan=0""")
				db.commit()
				if manualTemp>0 :
					cur.execute("""UPDATE User_Req SET Temp=0""")
					db.commit()
			else : #user wants fan on
				cur.execute("""UPDATE Conditions SET Heat=0, AC=0, Fan=1""")
				db.commit()
				if manualTemp>0 :
					cur.execute("""UPDATE User_Req SET Temp=0""")
					db.commit()
		elif userReqHeat==1 : #user wants home heated to target and we're too cold
			cur.execute("""UPDATE Conditions SET Heat=1, AC=0, Fan=1""")
			db.commit()
			
	#Home is warmer than target
	elif avgTemp>maxTemp :
		print ("AC is needed. Too hot at", avgTemp)
		if userReqAC==1 : #House is too warm, cool it
			cur.execute("""UPDATE Conditions SET Heat=0, AC=1, Fan=1""")
			db.commit()			
		elif userReqHeat==1 : #we're warm enough, let house cool naturally
			if userReqFan==0 : #auto fan
				cur.execute("""UPDATE Conditions SET Heat=0, AC=0, Fan=0""")
				db.commit()
				if manualTemp>0 :
					cur.execute("""UPDATE User_Req SET Temp=0""")
					db.commit()
			else : #user wants fan on
				cur.execute("""UPDATE Conditions SET Heat=0, AC=0, Fan=1""")
				db.commit()
				if manualTemp>0 :
					cur.execute("""UPDATE User_Req SET Temp=0""")
					db.commit()