#!/usr/bin/python
import MySQLdb
import time
import datetime
def convertTime(a):
	output=datetime.datetime.strptime(str(a), '%H:%M:%S')
	output=output.strftime("%H:%M:%S")
	return output

db = MySQLdb.connect(host="localhost", # your host, usually localhost
                     user="pi", # your username
                      passwd="raspberry", # your password
                      db="thermostat") # name of the data base

# you must create a Cursor object. It will let
#  you execute all the query you need
cur = db.cursor() 


	# pull generated temperatures from db
	#cur.execute("SELECT * FROM Temperatures")

	
	# store averaged temperture into the Conditions table
	#cur.execute("""UPDATE Conditions SET Temp=%s""",(avgTemp))
	#db.commit()

	# read stored average
	#cur.execute("SELECT * FROM Conditions")
	#for row in cur.fetchall() :
		#print row[0]
		#$avgTemp=row[0];

dow=time.strftime("%a")
print (dow)
currentTime=time.strftime("%H:%M:%S")
print (currentTime)
cur.execute("SELECT Target FROM Schedule WHERE DOW=%s AND %s BETWEEN Start AND Stop ",(dow, currentTime))
for row in cur.fetchall() :
	print (row[0])
